# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CZ88SDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CZ88SDKDemo
  pod 'CZ88SDK'

  target 'CZ88SDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CZ88SDKDemoUITests' do
    # Pods for testing
  end

end
